[project]
name = "sbc-g08-p2"
version = "0.1.0"
description = "Practica 2"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black",
    "click>=8.1.7",
    "toml>=0.10.2",
]

[tool.uv.sources]
black = { git = "https://github.com/psf/black" }
