[project]
name = "sbc-g08-p3"
version = "0.1.0"
description = "Practica 3"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=24.10.0",
    "click>=8.1.7",
    "matplotlib>=3.9.2",
    "networkx>=3.4.2",
    "pandas>=2.2.3",
    "tabulate>=0.9.0",
]
